# Generated by Django 5.0.3 on 2024-03-11 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(max_length=255)),
                (
                    "professor_type",
                    models.CharField(
                        choices=[
                            ("I", "Instructor"),
                            ("AP", "Assistant Professor"),
                            ("AOP", "Associate Professor"),
                            ("P", "Professor"),
                        ],
                        default="I",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Peer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("major", models.CharField(max_length=255)),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("UG", "Undergraduate"),
                            ("GR", "Graduate"),
                            ("PG", "Postgraduate"),
                            ("PHD", "Doctorate"),
                        ],
                        default="UG",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentored_projects",
                        to="TechAI.mentor",
                    ),
                ),
                (
                    "peers",
                    models.ManyToManyField(
                        related_name="peer_projects", to="TechAI.peer"
                    ),
                ),
                (
                    "publication",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="TechAI.publication",
                    ),
                ),
            ],
        ),
    ]
