# Generated by Django 5.0.3 on 2024-03-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='graduate_level',
        ),
        migrations.AddField(
            model_name='peer',
            name='degree_level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate'), ('PG', 'Postgraduate'), ('PHD', 'Doctorate')], default='UG', max_length=3),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='professor_type',
            field=models.CharField(choices=[('I', 'Instructor'), ('AP', 'Assistant Professor'), ('AOP', 'Associate Professor'), ('P', 'Professor')], default='I', max_length=3),
        ),
    ]
