# Generated by Django 5.0.3 on 2024-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechAI', '0002_remove_peer_graduate_level_peer_degree_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
